development:
  adapter: mysql2
  database: intelliclash
  pool: 5
  username: root
  password: root
  timeout: 5000
production:
  adapter: mysql2
  database: intelliclash
  pool: 5
  username: root
  password: root
  timeout: 5000
